using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tintelo.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class StoreAsGenerator : IIncrementalGenerator
{
	const string StoreAsAttributeName = "Tintelo.iOS.Models.Config.StoreAsAttribute";
	const string ObservablePropertyAttributeName = "CommunityToolkit.Mvvm.ComponentModel.ObservablePropertyAttribute";
	const string StorageTypeName = "global::Tintelo.iOS.Services.SimpleStorage";
	
	const string AttributeSource = """
	                               // <auto-generated/>
	                               #nullable enable
	                               namespace Tintelo.iOS.Models.Config;

	                               [global::System.AttributeUsage(
	                               	global::System.AttributeTargets.Property,
	                               	AllowMultiple = false,
	                               	Inherited = false)]
	                               internal sealed class StoreAsAttribute : global::System.Attribute
	                               {
	                               	public StoreAsAttribute(string key)
	                               	{
	                               		Key = key;
	                               	}

	                               	public StoreAsAttribute(string key, object? defaultValue)
	                               	{
	                               		Key = key;
	                               		DefaultValue = defaultValue;
	                               	}

	                               	public string Key { get; }

	                               	public object? DefaultValue { get; }
	                               }
	                               """;
	
	
	static StoredPropertyInfo? CreatePropertyInfo(
		GeneratorAttributeSyntaxContext context)
	{
		if (context.TargetSymbol is not IPropertySymbol property || context.Attributes.Length == 0)
			return null;

		AttributeData attribute = context.Attributes[0];
		string? key = attribute.ConstructorArguments.Length > 0
			? attribute.ConstructorArguments[0].Value as string
			: null;
		bool hasDefaultValue = attribute.ConstructorArguments.Length > 1;
		TypedConstant defaultValue = hasDefaultValue
			? attribute.ConstructorArguments[1]
			: default;

		return new(
			property,
			key,
			hasDefaultValue,
			defaultValue,
			context.TargetNode.GetLocation());
	}

	static void Execute(
		SourceProductionContext context,
		Compilation compilation,
		ImmutableArray<StoredPropertyInfo> properties)
	{
		foreach (var typeGroup in properties.GroupBy(static property => property.Property.ContainingType, SymbolEqualityComparer.Default))
		{
			List<StoredPropertyInfo> validProperties = new();
			Dictionary<string, StoredPropertyInfo> keys = new(StringComparer.Ordinal);

			foreach (StoredPropertyInfo property in typeGroup)
			{
				if (!HasAttribute(property.Property, ObservablePropertyAttributeName))
				{
					context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.MissingObservableProperty,
						property.Location,
						property.Property.Name));
					continue;
				}
				if (!IsSupportedContainingType(property.Property.ContainingType))
				{
					context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidContainingType,
						property.Location,
						property.Property.Name));
					continue;
				}
				if (string.IsNullOrWhiteSpace(property.Key))
				{
					context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidStorageKey,
						property.Location,
						property.Property.Name));
					continue;
				}
				if (!IsDefaultValueCompatible(compilation, property))
				{
					context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.InvalidDefaultValue,
						property.Location,
						property.Property.Name,
						property.Property.Type.ToDisplayString()));
					continue;
				}
				if (keys.TryGetValue(property.Key!, out StoredPropertyInfo? existingProperty))
				{
					context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.DuplicateStorageKey,
						property.Location,
						property.Key,
						existingProperty.Property.Name));
					continue;
				}

				keys.Add(property.Key!, property);
				validProperties.Add(property);
			}

			if (validProperties.Count == 0)
				continue;

			INamedTypeSymbol containingType = validProperties[0].Property.ContainingType;
			string source = GenerateTypeSource(containingType, validProperties);
			string hintName = containingType.ToDisplayString()
				.Replace("global::", string.Empty)
				.Replace('.', '_')
				+ ".StoreAs.g.cs";

			context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
		}
	}

	static bool HasAttribute(
		IPropertySymbol property,
		string metadataName) =>
		property.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == metadataName);

	static bool IsSupportedContainingType(
		INamedTypeSymbol type)
	{
		if (type.ContainingType is not null || type.TypeParameters.Length != 0 || type.TypeKind != TypeKind.Class)
			return false;

		return type.DeclaringSyntaxReferences
			.Select(static reference => reference.GetSyntax())
			.OfType<TypeDeclarationSyntax>()
			.Any(static declaration => declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
	}

	static bool IsDefaultValueCompatible(
		Compilation compilation,
		StoredPropertyInfo property)
	{
		if (!property.HasDefaultValue)
			return true;

		if (property.DefaultValue.IsNull)
			return property.Property.Type.IsReferenceType ||
				property.Property.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

		if (property.DefaultValue.Type is null)
			return false;

		return compilation.ClassifyConversion(property.DefaultValue.Type, property.Property.Type).IsImplicit;
	}

	static bool IsNonNullableReference(
		ITypeSymbol type) =>
		type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.NotAnnotated;

	static string GenerateTypeSource(
		INamedTypeSymbol containingType,
		IReadOnlyList<StoredPropertyInfo> properties)
	{
		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");

		if (!containingType.ContainingNamespace.IsGlobalNamespace)
		{
			builder.Append("namespace ")
				.Append(containingType.ContainingNamespace.ToDisplayString())
				.AppendLine(";")
				.AppendLine();
		}

		builder.Append("partial class ")
			.Append(EscapeIdentifier(containingType.Name))
			.AppendLine()
			.AppendLine("{")
			.Append("\tprivate ")
			.Append(StorageTypeName)
			.AppendLine("? __storeAsStorage;")
			.AppendLine();

		IReadOnlyList<StoredPropertyInfo> initializedNonNullableProperties = properties
			.Where(static property =>
				IsNonNullableReference(property.Property.Type) &&
				property.HasDefaultValue &&
				!property.DefaultValue.IsNull)
			.ToArray();

		if (initializedNonNullableProperties.Count > 0)
		{
			builder.Append("\t[global::System.Diagnostics.CodeAnalysis.MemberNotNull(");
			for (int index = 0; index < initializedNonNullableProperties.Count; index++)
			{
				if (index > 0)
					builder.Append(", ");

				builder.Append("nameof(")
					.Append(EscapeIdentifier(initializedNonNullableProperties[index].Property.Name))
					.Append(')');
			}
			builder.AppendLine(")]");
		}

		builder.Append("\tprivate void InitializeStoredProperties(")
			.Append(StorageTypeName)
			.AppendLine(" storage)")
			.AppendLine("\t{")
			.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(storage);")
			.AppendLine()
			.AppendLine("\t\tif (__storeAsStorage is not null)")
			.AppendLine("\t\t\tthrow new global::System.InvalidOperationException(\"Stored properties have already been initialized.\");")
			.AppendLine()
			.AppendLine("\t\t__storeAsStorage = storage;");

		foreach (StoredPropertyInfo property in properties)
		{
			builder.Append("\t\t")
				.Append(EscapeIdentifier(property.Property.Name))
				.Append(" = storage.GetValue<")
				.Append(property.Property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
				.Append(">(")
				.Append(SymbolDisplay.FormatLiteral(property.Key!, quote: true))
				.Append(", ")
				.Append(GetDefaultValueExpression(property))
				.AppendLine(");");
		}

		builder.AppendLine()
			.AppendLine("\t\tPropertyChanged += __StoreAsPropertyChanged;")
			.AppendLine("\t}")
			.AppendLine()
			.AppendLine("\tprivate void __StoreAsPropertyChanged(")
			.AppendLine("\t\tobject? sender,")
			.AppendLine("\t\tglobal::System.ComponentModel.PropertyChangedEventArgs args)")
			.AppendLine("\t{")
			.AppendLine("\t\tvar storage = __storeAsStorage!;")
			.AppendLine()
			.AppendLine("\t\tswitch (args.PropertyName)")
			.AppendLine("\t\t{");

		foreach (StoredPropertyInfo property in properties)
		{
			string propertyName = EscapeIdentifier(property.Property.Name);
			builder.Append("\t\t\tcase nameof(")
				.Append(propertyName)
				.AppendLine("):")
				.Append("\t\t\t\tstorage.SetValue(")
				.Append(SymbolDisplay.FormatLiteral(property.Key!, quote: true))
				.Append(", ")
				.Append(propertyName)
				.AppendLine(");")
				.AppendLine("\t\t\t\tbreak;");
		}

		builder.AppendLine("\t\t}")
			.AppendLine("\t}")
			.AppendLine("}");

		return builder.ToString();
	}

	static string GetDefaultValueExpression(
		StoredPropertyInfo property)
	{
		string propertyType = property.Property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		if (!property.HasDefaultValue || property.DefaultValue.IsNull)
			return $"default({propertyType})";

		return $"({propertyType}){FormatConstant(property.DefaultValue)}";
	}

	static string FormatConstant(
		TypedConstant constant)
	{
		if (constant.Kind == TypedConstantKind.Enum)
			return FormatPrimitive(constant.Value!);

		return constant.Value switch
		{
			string value => SymbolDisplay.FormatLiteral(value, quote: true),
			char value => SymbolDisplay.FormatLiteral(value, quote: true),
			bool value => value ? "true" : "false",
			float value => value.ToString("R", CultureInfo.InvariantCulture) + "F",
			double value => value.ToString("R", CultureInfo.InvariantCulture) + "D",
			_ => FormatPrimitive(constant.Value!)
		};
	}

	static string FormatPrimitive(
		object value) => value switch
	{
		sbyte number => number.ToString(CultureInfo.InvariantCulture),
		byte number => number.ToString(CultureInfo.InvariantCulture),
		short number => number.ToString(CultureInfo.InvariantCulture),
		ushort number => number.ToString(CultureInfo.InvariantCulture),
		int number => number.ToString(CultureInfo.InvariantCulture),
		uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
		long number => number.ToString(CultureInfo.InvariantCulture) + "L",
		ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
		_ => throw new InvalidOperationException($"Unsupported attribute constant type '{value.GetType()}'.")
	};

	static string EscapeIdentifier(
		string name) =>
		SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

	
	public void Initialize(
		IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static output =>
			output.AddSource("StoreAsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

		IncrementalValuesProvider<StoredPropertyInfo> properties = context.SyntaxProvider.ForAttributeWithMetadataName(
				StoreAsAttributeName,
				static (node, _) => node is PropertyDeclarationSyntax,
				static (attributeContext, _) => CreatePropertyInfo(attributeContext))
			.Where(static property => property is not null)
			.Select(static (property, _) => property!);

		context.RegisterSourceOutput(
			context.CompilationProvider.Combine(properties.Collect()),
			static (output, source) => Execute(output, source.Left, source.Right));
	}
}
