<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-ios</TargetFramework>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<NeutralLanguage>en</NeutralLanguage>
		<SupportedOSPlatformVersion>26.0</SupportedOSPlatformVersion>
		
		<ComposerIconName>AppIcon</ComposerIconName>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<CodesignKey>iPhone Developer</CodesignKey>
		<EnableHotReload>true</EnableHotReload>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<CodesignKey>iPhone Developer</CodesignKey>
		<TrimMode>full</TrimMode>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SkeleKit.iOS" Version="0.1.8"/>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Aigamo.ResXGenerator" Version="4.4.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\" />
	</ItemGroup>

	<PropertyGroup>
		<ResXGenerator_NullForgivingOperators>true</ResXGenerator_NullForgivingOperators>
	</PropertyGroup>

	<Import Project="Resources\IconComposer.targets" />
</Project>
