<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-ios27.0</TargetFramework>
		<NoWarn>$(NoWarn);XCODE_27_0_PREVIEW</NoWarn>
		
		<OutputType>Exe</OutputType>
		<ApplicationId>com.icysnex.tintelo</ApplicationId>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<NeutralLanguage>en</NeutralLanguage>
		<SupportedOSPlatformVersion>18.0</SupportedOSPlatformVersion>
		
		<AppIcon>AppIcon</AppIcon>
		<ValidateXcodeVersion>true</ValidateXcodeVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<CodesignKey>iPhone Developer</CodesignKey>
		<EnableHotReload>true</EnableHotReload>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<CodesignKey>iPhone Developer</CodesignKey>
		<TrimMode>full</TrimMode>
	</PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="SkeleKit.iOS" Version="0.1.14" />-->
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
		<PackageReference Include="Aigamo.ResXGenerator" Version="4.4.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\SkeleKit\Source\Framework\SkeleKit.Generators\SkeleKit.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\SkeleKit\Source\Framework\SkeleKit.iOS\SkeleKit.iOS.csproj" />
		
		<ProjectReference Include="..\Tintelo.Generators\Tintelo.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<Import Project="..\..\SkeleKit\Source\Framework\SkeleKit.iOS\build\SkeleKit.iOS.targets" />
	<PropertyGroup>
		<ResXGenerator_NullForgivingOperators>true</ResXGenerator_NullForgivingOperators>
	</PropertyGroup>
</Project>
