<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-ios</TargetFramework>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>

		<SupportedOSPlatformVersion>18.0</SupportedOSPlatformVersion>
		
		<ComposerIconName>AppIcon</ComposerIconName>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<CodesignKey>iPhone Developer</CodesignKey>
		<EnableHotReload>true</EnableHotReload>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<CodesignKey>iPhone Developer</CodesignKey>
		<TrimMode>full</TrimMode>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="SkeleKit.iOS" Version="0.1.5"/>
	</ItemGroup>

	<Import Project="Resources\IconComposer.targets" />
</Project>
